version: "3.7"
services:
  postgres_register:
    container_name: postgres_register_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: register
      POSTGRES_PASSWORD: register
    ports:
      - "5432:5432"

  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5433:5432"

  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:12.0.4
    environment:
      #build sem e depois volta
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"

  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.22
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus_ifood:
    container_name: prometheus_ifood
    image: prometheus-ifood
    network_mode: "host"

  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana:7.5.3
    network_mode: "host"

  artemis_ifood:
    container_name: artemis_ifood
    image: vromero/activemq-artemis:2.16.0
    network_mode: "host"
    environment:
      ARTEMIS_USERNAME: admin
      ARTEMIS_PASSWORD: admin

  mongodb_ifood:
    container_name: mongodb_ifood
    image: mongo:4.4.5
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: order
      MONGO_INITDB_ROOT_PASSWORD: order
      MONGO_INITDB_DATABASE: order