
-- public.restaurant definition

-- Drop table

-- DROP TABLE public.restaurant;

CREATE TABLE public.restaurant (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    cnpj varchar(255) NULL,
    dateupdate timestamp NULL,
    datecreation timestamp NULL,
    name varchar(255) NULL,
    owner varchar(255) NULL,
    localization_id int8 NULL,
    CONSTRAINT restaurant_pkey PRIMARY KEY (id)
);


-- public.restaurant foreign keys

ALTER TABLE public.restaurant ADD CONSTRAINT fkdfbggt9ievc4ev74wl3tdnscl FOREIGN KEY (localization_id) REFERENCES localization(id);

-- public.dish definition

-- Drop table

-- DROP TABLE public.dish;

CREATE TABLE public.dish (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    description varchar(255) NULL,
    name varchar(255) NULL,
    price numeric(19,2) NULL,
    restaurant_id int8 NULL,
    CONSTRAINT dish_pkey PRIMARY KEY (id)
);


-- public.dish foreign keys

ALTER TABLE public.dish ADD CONSTRAINT fk43yo4ddilkvn6ebgfcx2vnqs7 FOREIGN KEY (restaurant_id) REFERENCES restaurant(id);